### PR TITLE
pyelftools/container.py: fix broken import

### PR DESCRIPTION
**Pull request by michaelbrownuc**
This PR fixes an import that breaks during project creation in Python 3.10.

### CODE REVIEW

**Comment by vitalych** [comment]
Thanks! Is this fixed upstream? Perhaps we could rebase and reapply S2E commits on top.

**Comment by vitalych** [comment]
https://github.com/S2E/s2e-env/issues/467

**Comment by michaelbrownuc** [comment]
I just took a look this is fixed upstream. Given that this fork is >150 commits behind the head repo it probably makes sense to update it.  

I'm not familiar with the S2E specific commits here - are they still necessary?

**Comment by vitalych** [comment]
> I'm not familiar with the S2E specific commits here - are they still necessary?

If not fixed in upstream, then yes. I haven't looked at pyelftools in a couple years, so I don't know. You could try to reapply them on top of master, see if it works cleanly.

**Comment by michaelbrownuc** [comment]
Taking a look at the S2E specific commits, it doesn't look like they are complex. I'll give rebasing a shot and see what happens.

**Comment by vitalych** [comment]
Merging the quick fix before we have the more complex upgrade.

**Pull request merged**
